[floor_directory]
filename = floor_directory.csv
case_sensitive_match = false

[employee_directory]
filename = employee_directory.csv
case_sensitive_match = false

[system_codes]
filename = system_codes.csv
case_sensitive_match = false
