[install]
is_configured = 1
build = 23

[ui]
is_visible = true
label = Nakatomi Heist
supported_themes = dark

[launcher]
author = Nakatomi Vault Heist Project
description = A Splunk-powered inverse escape room. Five acts, 26 tasks, one vault heist.
version = 2.3.0

[package]
id = nakatomi_heist
check_for_updates = false
