[nakatomi_access]
homePath = $SPLUNK_DB/nakatomi_access/db
coldPath = $SPLUNK_DB/nakatomi_access/colddb
thawedPath = $SPLUNK_DB/nakatomi_access/thaweddb

[nakatomi_vault]
homePath = $SPLUNK_DB/nakatomi_vault/db
coldPath = $SPLUNK_DB/nakatomi_vault/colddb
thawedPath = $SPLUNK_DB/nakatomi_vault/thaweddb

[nakatomi_building]
homePath = $SPLUNK_DB/nakatomi_building/db
coldPath = $SPLUNK_DB/nakatomi_building/colddb
thawedPath = $SPLUNK_DB/nakatomi_building/thaweddb
