[batch://$SPLUNK_HOME/etc/apps/nakatomi_heist/data/nakatomi_access_badge.log]
disabled = false
index = nakatomi_access
sourcetype = nakatomi:access:badge
host = nakatomi-bms
move_policy = sinkhole

[batch://$SPLUNK_HOME/etc/apps/nakatomi_heist/data/nakatomi_access_door.log]
disabled = false
index = nakatomi_access
sourcetype = nakatomi:access:door
host = nakatomi-bms
move_policy = sinkhole

[batch://$SPLUNK_HOME/etc/apps/nakatomi_heist/data/nakatomi_vault_attempt.log]
disabled = false
index = nakatomi_vault
sourcetype = nakatomi:vault:attempt
host = nakatomi-bms
move_policy = sinkhole

[batch://$SPLUNK_HOME/etc/apps/nakatomi_heist/data/nakatomi_vault_system.log]
disabled = false
index = nakatomi_vault
sourcetype = nakatomi:vault:system
host = nakatomi-bms
move_policy = sinkhole

[batch://$SPLUNK_HOME/etc/apps/nakatomi_heist/data/nakatomi_building_hvac.log]
disabled = false
index = nakatomi_building
sourcetype = nakatomi:building:hvac
host = nakatomi-bms
move_policy = sinkhole

[batch://$SPLUNK_HOME/etc/apps/nakatomi_heist/data/nakatomi_building_security.log]
disabled = false
index = nakatomi_building
sourcetype = nakatomi:building:security
host = nakatomi-bms
move_policy = sinkhole

[batch://$SPLUNK_HOME/etc/apps/nakatomi_heist/data/nakatomi_security_camera.log]
disabled = false
index = nakatomi_building
sourcetype = nakatomi:security:camera
host = nakatomi-bms
move_policy = sinkhole

[batch://$SPLUNK_HOME/etc/apps/nakatomi_heist/data/nakatomi_building_elevator.log]
disabled = false
index = nakatomi_building
sourcetype = nakatomi:building:elevator
host = nakatomi-bms
move_policy = sinkhole

[batch://$SPLUNK_HOME/etc/apps/nakatomi_heist/data/nakatomi_building_power.log]
disabled = false
index = nakatomi_building
sourcetype = nakatomi:building:power
host = nakatomi-bms
move_policy = sinkhole

[batch://$SPLUNK_HOME/etc/apps/nakatomi_heist/data/nakatomi_comms_radio.log]
disabled = false
index = nakatomi_comms
sourcetype = nakatomi:comms:radio
host = nakatomi-bms
move_policy = sinkhole

[batch://$SPLUNK_HOME/etc/apps/nakatomi_heist/data/nakatomi_comms_phone.log]
disabled = false
index = nakatomi_comms
sourcetype = nakatomi:comms:phone
host = nakatomi-bms
move_policy = sinkhole
