[nakatomi:access:badge]
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%z
MAX_TIMESTAMP_LOOKAHEAD = 32
KV_MODE = auto
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)

[nakatomi:access:door]
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%z
MAX_TIMESTAMP_LOOKAHEAD = 32
KV_MODE = auto
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)

[nakatomi:vault:attempt]
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%z
MAX_TIMESTAMP_LOOKAHEAD = 32
KV_MODE = auto
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)

[nakatomi:vault:system]
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%z
MAX_TIMESTAMP_LOOKAHEAD = 32
KV_MODE = auto
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)

[nakatomi:building:hvac]
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%z
MAX_TIMESTAMP_LOOKAHEAD = 32
KV_MODE = auto
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)

[nakatomi:building:security]
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%z
MAX_TIMESTAMP_LOOKAHEAD = 32
KV_MODE = auto
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)

[nakatomi_vault_physical]
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%z
KV_MODE = json
SHOULD_LINEMERGE = false
